### PR TITLE
Fixes #7205: Skip lsb_release on SLES, as it is missing the Service Pack

### PR DESCRIPTION
**Pull request by matya**

### CODE REVIEW

**Comment by VinceMacBuche** [comment]
Thanks Matya! 

Unfortunately, the patch does not apply on fusioninventory :( ( it needs full path to the changed file)

    Applying patches/fusioninventory/0012-fix-suse-sles-lsb-release.patch... on FusionInventory
    can't find file to patch at input line 3
    Perhaps you used the wrong -p or --strip option?
    The text leading up to this was:
    --------------------------
    |--- LSB.pm.orig	2015-10-13 16:08:20.000000000 +0200
    |+++ LSB.pm	2015-10-13 16:08:34.000000000 +0200
    --------------------------


to test if patches apply just run:

    cd rudder-agent/SOURCES
    make ./fusioninventory-agent

The full path is lib/FusionInventory/Agent/Task/Inventory/Linux/Distro/LSB.pm

Once your patch is okay, you can run the following command:

    git add your-patch
    git commit --amend
    git push origin -f

This will automatically update the Pull request :)

**Comment by VinceMacBuche** [comment]
to create your patch, run this (better to rm your current patch):

    cd rudder-agent/SOURCES
    make ./fusioninventory-agent
    cp fusioninventory-agent fusioninventory-agent-new
    <do your changes fusioninventory-agent-new>
    diff -ur fusioninventory-agent/lib/ fusioninventory-agent-new/lib/ > patches/fusioninventory/0012-fix-suse-sles-lsb-release.patch

**Comment by matya** [comment]
Updated, sorry.

**Comment by VinceMacBuche** [comment]
Awesome @matya ! Maybe the patching process should be documented (and how to test it ...)

**Comment by matya** [comment]
Maybe :-) Or I could look in one existing and see that it's relative to lib...

**Comment by ncharles** [comment]
Awesome, thank you so much @matya

**Pull request merged**
