### PR TITLE
Fixes #13852: Merge packages into one

### PR DESCRIPTION
**Pull request by peckpeck**
https://issues.rudder.io/issues/13852

### CODE REVIEW

**Comment by amousset** [comment]
Do you intend to make a different PR for ncf-api-venv removal?

**Comment by peckpeck** [comment]
no, it's just that i forgot to remove directories

**Comment by peckpeck** [comment]
Commit modified

**Comment by peckpeck** [comment]
Commit modified

**Comment by peckpeck** [comment]
Commit modified

**Pull request merged**
