### PR TITLE
Fixes #8822: Missing BuildRequires for rudder-agent : pam-devel

### PR DESCRIPTION
**Pull request by amousset**
https://www.rudder-project.org/redmine/issues/8822

### CODE REVIEW

**Comment by amousset** [comment]
Commit modified

**Comment by amousset** [comment]
ping @jooooooon

**Comment by jooooooon** [comment]
Ah, sorry, I should have answered this earlier. I just don't understand this - we have been building the agent on 2.11 for years, why would we need a new BuildRequires now?

The ticket doesn't help me understand the context either :)

**Comment by amousset** [comment]
It is installed on every builder because of https://github.com/Normation/rudder-packages/blob/master/rudder-agent/SOURCES/.dependencies, and also in the requirements for the deb package, but missing from the spec file.

**Comment by jooooooon** [comment]
Ah, I see! Thanks for explaining. For future reference, this is *exactly* what should be written in the ticket itself.

**Comment by amousset** [comment]
OK, merging this PR

**Pull request merged**
