### PR TITLE
Fixes #25305: Build the system-updates module

### PR DESCRIPTION
**Pull request by amousset**
https://issues.rudder.io/issues/25305

### CODE REVIEW

**Comment by amousset** [comment]
PR updated with a new commit

**Comment by amousset** [comment]
PR updated with a new commit

**Comment by amousset** [comment]
PR updated with a new commit

**Comment by amousset** [comment]
PR updated with a new commit

**Comment by amousset** [comment]
PR updated with a new commit

**Review by peckpeck — APPROVED** [review]

**Pull request merged**
