### PR TITLE
Fixes #7074: Merge postinstall into a single script

### PR DESCRIPTION
**Pull request by peckpeck**
https://www.rudder-project.org/redmine/issues/7074

### CODE REVIEW

**Comment by peckpeck** [comment]
PR updated

**Comment by Kegeruneku** [comment]
Hmmm, don't you think that /opt/rudder/bin/rudder-postinstall should be put elsewhere, something like /opt/rudder/share/rudder-agent-postinst ?

**Comment by Kegeruneku** [comment]
(apart from this, it looks OK)

**Comment by peckpeck** [comment]
PR updated

**Comment by peckpeck** [comment]
why not

**Comment by peckpeck** [comment]
PR updated

**Comment by Kegeruneku** [comment]
Hum, maybe /opt/rudder/share/postinst/rudder-agent instead of /opt/rudder/share/rudder-agent-postinst

(postinst, or postinstall, the choice is yours :D)

**Comment by Kegeruneku** [comment]
(thanksà

**Comment by peckpeck** [comment]
PR updated

**Comment by Kegeruneku** [comment]
Accepted !

**Pull request merged**
