### PR TITLE
Fixes #6832: Preliminary support for solaris package

### PR DESCRIPTION
**Pull request by peckpeck**
https://www.rudder-project.org/redmine/issues/6832

### CODE REVIEW

**Comment by Kegeruneku** [comment]
Is it possible to:
* mv SOLARIS solaris
* add an argument to build.sh on solaris to pass the version as a parameter (much tidier that sed'ing all the time ^^)

**Comment by Kegeruneku** [comment]
thx

**Comment by peckpeck** [comment]
PR updated

**Comment by Kegeruneku** [comment]
Eeyup.

**Comment by peckpeck** [comment]
PR updated

**Comment by peckpeck** [comment]
Self merging

**Pull request merged**
