### PR TITLE
Fixes #6598: rudder selinux module is not working

### PR DESCRIPTION
**Pull request by VinceMacBuche**
http://www.rudder-project.org/redmine/issues/6598

### CODE REVIEW

**Comment by peckpeck** [comment]
You should compile the .pp from the .te with a command in the packaging instead of including it as is in the repository.

**Comment by VinceMacBuche** [comment]
I'm not sure where I should put that command 

It is advised to compile the policy in the install section in rpm 

I guess it should be done in the debian/rules too

**Comment by VinceMacBuche** [comment]
PR updated

**Comment by VinceMacBuche** [comment]
Soem docs about packaging selinux policy 

https://fedoraproject.org/wiki/SELinux_Policy_Modules_Packaging_Draft

https://fedoraproject.org/wiki/PackagingDrafts/SELinux

**Comment by VinceMacBuche** [comment]
* Still need the debian one
* to remove rudder-webapp.pp
* Maybe some requires are needed in the specfile

**Comment by VinceMacBuche** [comment]
PR updated

**Comment by VinceMacBuche** [comment]
pp file removed

**Comment by VinceMacBuche** [comment]
PR updated

**Comment by peckpeck** [comment]
That's fine for me

**Pull request merged**
