### PR TITLE
Fixes #22267: on rhel postinst uses yum creating a deadlock

### PR DESCRIPTION
**Pull request by peckpeck**
https://issues.rudder.io/issues/22267

### CODE REVIEW

**Review by amousset — APPROVED** [review]

**Comment by peckpeck** [comment]
OK, merging this PR

**Comment by peckpeck** [comment]
OK, merging this PR

**Comment by peckpeck** [comment]
OK, merging this PR

**Comment by peckpeck** [comment]
OK, merging this PR

**Pull request merged**
