### PR TITLE
Fixes #6590:  cfengine context is not updated properly when doing multiple indivudual package actions for 3.0

### PR DESCRIPTION
**Pull request by amousset**
http://www.rudder-project.org/redmine/issues/6590

### CODE REVIEW

**Comment by ncharles** [comment]
awesomeness overflow !

**Comment by ncharles** [comment]
@amousset you should target branch 2.11, as the problem exists also in this branch

**Comment by ncharles** [comment]
see also https://github.com/Normation/rudder-packages/pull/656

@amousset is it necessary to have one patch per branch ?

**Comment by peckpeck** [comment]
Yes since our naming and numbering of patches have changed between branches.

**Comment by ncharles** [comment]
this numbering is quite stupid, it will always prevent direct merge between branches...

**Comment by ncharles** [comment]
the commit is missing the actual application of patch, in the makefile

**Pull request merged**
