### PR TITLE
Fixes #14945: Missing index in ldap directory 

### PR DESCRIPTION
**Pull request by ncharles**
https://issues.rudder.io/issues/14945

### CODE REVIEW

**Comment by fanf** [comment]
I would like to check on load plateform these changes before merging them.

**Comment by fanf** [comment]
I would like to check on load plateform these changes before merging them.

**Comment by ncharles** [comment]
impact is totally null on load platform: neither better nor worse :/

**Comment by fanf** [comment]
Should we merge that? If the impact if null, it seems like a risk to add them (we don't know the impact on write, which can be important). 
Perhaps we should just not do anything?

**Comment by ncharles** [comment]
on some platform it's faster, but indeed the impact is too risky (or at least feels risky). Closing

**Pull request closed without merging**
