### PR TITLE
Fixes #8026: Slackware support for FusionInventory-Agent

### PR DESCRIPTION
**Pull request by peckpeck**
https://www.rudder-project.org/redmine/issues/8026

### CODE REVIEW

**Comment by jooooooon** [comment]
@peckpeck Please provide this patch upstream to FusionInventory

**Comment by amousset** [comment]
Ok, merging.

**Comment by jooooooon** [comment]
Please check it's sent upstream to FusionInventory.

**Comment by peckpeck** [comment]
upstream patch https://github.com/fusioninventory/fusioninventory-agent/pull/93

**Pull request merged**
