### PR TITLE
Fixes #18747: missing python3-setuptools dependency on relay on sles15 and rhel6

### PR DESCRIPTION
**Pull request by VinceMacBuche**
https://issues.rudder.io/issues/18747

### CODE REVIEW

**Comment by VinceMacBuche** [comment]
PR updated with a new commit

**Comment by VinceMacBuche** [comment]
PR updated with a new commit

**Review by peckpeck — APPROVED** [review]

**Review by amousset — APPROVED** [review]

**Comment by VinceMacBuche** [comment]
OK, squash merging this PR

**Comment by VinceMacBuche** [comment]
OK, squash merging this PR

**Comment by VinceMacBuche** [comment]
This was merged but pr was not closed I'm closing the issue

**Comment by fanf** [comment]
Closing, as for previous comment.

**Pull request closed without merging**
