### PR TITLE
Fixes #13174: can't upgrade debian package if /bin/systemd exist but sysv is used

### PR DESCRIPTION
**Pull request by amousset**
https://www.rudder-project.org/redmine/issues/13174

### CODE REVIEW

**Comment by amousset** [comment]
I did not used the proposed solution but the one used by CFEngine for systemd detection, what do you think?

**Comment by amousset** [comment]
(Full CFEngine solution is to follow the symlinks and check the command end in "/systemd")

**Comment by peckpeck** [comment]
This pr is not mergeable anymore

**Comment by amousset** [comment]
Commit modified

**Comment by amousset** [comment]
@peck updated

**Pull request merged**
