### PR TITLE
Fixes #7679: All the files in /opt/rudder/share/tools should not be executable

### PR DESCRIPTION
**Pull request by jooooooon**
https://www.rudder-project.org/redmine/issues/7679

### CODE REVIEW

**Comment by peckpeck** [comment]
So this entire files does nothing excepting checking its arguments.
Shouldn't it be simply removed ?

**Comment by jooooooon** [comment]
Ah, yes, indeed it should. Well spotted, thanks.

**Comment by jooooooon** [comment]
PR updated

**Comment by peckpeck** [comment]
OK, merging

**Pull request merged**
