### PR TITLE
Fixes #6713: Add a caching system to rudder build system

### PR DESCRIPTION
**Pull request by peckpeck**
https://www.rudder-project.org/redmine/issues/6713

Replacing previous PR: https://github.com/Normation/rudder-packages/pull/680

### CODE REVIEW

**Comment by peckpeck** [comment]
PR updated

**Comment by peckpeck** [comment]
PR updated

**Comment by peckpeck** [comment]
PR updated

**Comment by peckpeck** [comment]
@Kegeruneku finally after all these updates, you can review it !

**Comment by VinceMacBuche** [comment]
To me this is ok !!

**Comment by Kegeruneku** [comment]
Holy f*ck that's a big PR :dancer:

**Comment by Kegeruneku** [comment]
Yolo

**Pull request merged**
