### PR TITLE
Fixes #14022: Update rudder server relay to match modern packaging recommendation

### PR DESCRIPTION
**Pull request by peckpeck**
https://issues.rudder.io/issues/14022

### CODE REVIEW

**Comment by peckpeck** [comment]
Commit modified

**Comment by amousset** [comment]
Looks like rudder-server-relay-postinst is missing

**Comment by peckpeck** [comment]
too bad

**Comment by peckpeck** [comment]
Commit modified

**Comment by peckpeck** [comment]
OK, squash merging this PR

**Pull request merged**
