### PR TITLE
Fixes #6263: Disable other init scripts in rudder-server-root to prev…

### PR DESCRIPTION
**Pull request by Kegeruneku**
…ent issues in startup ordering

Ticket: http://www.rudder-project.org/redmine/issues/6263

To be merged in 2.11

### CODE REVIEW

**Comment by VinceMacBuche** [comment]
Ok great!

**Comment by VinceMacBuche** [comment]
Hmm wait, when techniques needs to restart processes, do they use those scripts ?

**Comment by Kegeruneku** [comment]
Yes. Disabling them in rc.d does not mean they are not usable any more of course :)

**Comment by Kegeruneku** [comment]
Just that they will not be called during system startup anymore.

**Comment by VinceMacBuche** [comment]
ha ok, it removed them from the startup not from the init scripts ;)

**Comment by Kegeruneku** [comment]
Yes. The "remove" argument from update-rc.d is ... kinda misleading.

**Comment by VinceMacBuche** [comment]
Merging then!

**Pull request merged**
