### PR TITLE
Fixes #18891: Upgrade failed from 5.0.20 to 6.1.9 on SLES

### PR DESCRIPTION
**Pull request by amousset**
https://issues.rudder.io/issues/18891

### CODE REVIEW

**Comment by amousset** [comment]
not enough

**Comment by amousset** [comment]
PR updated with a new commit

**Comment by amousset** [comment]
PR updated with a new commit

**Comment by amousset** [comment]
PR updated with a new commit

**Review by peckpeck — APPROVED** [review]

**Comment by amousset** [comment]
OK, squash merging this PR

**Pull request merged**
