### PR TITLE
Fixes #7241: Patch not applied on fusion inventory

### PR DESCRIPTION
**Pull request by VinceMacBuche**
https://www.rudder-project.org/redmine/issues/7241

### CODE REVIEW

**Comment by VinceMacBuche** [comment]
Closing, need to test it before

**Comment by VinceMacBuche** [comment]
PR updated

**Comment by VinceMacBuche** [comment]
Patch is not working, OSNAME does not exists ... generic file is not ok

**Comment by VinceMacBuche** [comment]
PR updated

**Comment by Kegeruneku** [comment]
You 100% sure it works this time ? :smirk:

**Comment by VinceMacBuche** [comment]
It is working, unless it would be closed :)

At least it would be better than what it was before ...

**Comment by peckpeck** [comment]
OK Good

**Pull request merged**
