### PR TITLE
Fixes #19362: Add ci checks for packages

### PR DESCRIPTION
**Pull request by amousset**
https://issues.rudder.io/issues/19362

### CODE REVIEW

**Comment by amousset** [comment]
Do not merge

**Comment by amousset** [comment]
PR updated with a new commit

**Comment by amousset** [comment]
PR updated with a new commit

**Comment by amousset** [comment]
PR updated with a new commit

**Comment by amousset** [comment]
PR updated with a new commit

**Comment by amousset** [comment]
PR updated with a new commit

**Comment by amousset** [comment]
PR updated with a new commit

**Comment by amousset** [comment]
PR updated with a new commit

**Review by peckpeck — APPROVED** [review]

**Comment by amousset** [comment]
OK, squash merging this PR

**Pull request merged**
