### PR TITLE
Fixes #6713: Add a caching system to rudder build system

### PR DESCRIPTION
**Pull request by peckpeck**
https://www.rudder-project.org/redmine/issues/6713

### CODE REVIEW

**Comment by Kegeruneku** [comment]
This looks AWESOME :dancer:

**Comment by peckpeck** [comment]
PR updated

**Comment by peckpeck** [comment]
PR updated

**Comment by peckpeck** [comment]
PR updated

**Comment by peckpeck** [comment]
PR updated

**Comment by peckpeck** [comment]
PR replaced by https://github.com/Normation/rudder-packages/pull/685

**Pull request closed without merging**
