### PR TITLE
Fixes #20475: Wrong version/hash for openssl

### PR DESCRIPTION
**Pull request by VinceMacBuche**
https://issues.rudder.io/issues/20475

### CODE REVIEW

**Review by amousset — APPROVED** [review]

**Comment by VinceMacBuche** [comment]
OK, merging this PR

**Comment by amousset** [comment]
OK, merging this PR

**Comment by VinceMacBuche** [comment]
OK, merging this PR

**Comment by VinceMacBuche** [comment]
OK, merging this PR

**Pull request merged**
