### PR TITLE
Fixes #8328: Update fusioninventory to 2.3.17

### PR DESCRIPTION
**Pull request by amousset**
https://www.rudder-project.org/redmine/issues/8328

### CODE REVIEW

**Comment by amousset** [comment]
We still need to:
* Upstream some changes
* Test inventories, specially for AIX, as the upstream code is not exactly what was in our patches

**Comment by amousset** [comment]
We should probably wait for successful 3.3 builds to merge this one.

**Comment by peckpeck** [comment]
Yes

**Comment by jooooooon** [comment]
Ping @amousset - are the builds on master now successful? If so, could you rebase this PR so we could merge it?

**Comment by amousset** [comment]
I did not saw a valid on 3.3 for now... But I did not test this recently.

**Comment by amousset** [comment]
Commit modified

**Comment by amousset** [comment]
Rebased, it was only the CFEngine version.

**Pull request merged**
