### PR TITLE
Fixes #8054: node-to-relay fails to reload policy when proxy is set

### PR DESCRIPTION
**Pull request by peckpeck**
https://www.rudder-project.org/redmine/issues/8054

### CODE REVIEW

**Comment by amousset** [comment]
Shouldn't we add this to all HTTP calls to local API (rudder server reload-*, the /status call in rudder agent, etc.) ?

**Comment by peckpeck** [comment]
yes, but most of them should already be done.
Can you find one ?

**Comment by amousset** [comment]
I see:
- https://github.com/Normation/rudder-techniques/blob/master/techniques/system/server-roles/1.0/technique-reload.st#L60
- https://github.com/Normation/rudder-techniques/blob/master/initial-promises/node-server/server-roles/1.0/alive-check.cf#L57
- https://github.com/Normation/rudder-agent/pull/54/files#diff-ab7a4a234a368e74ff367371269d02dcR7

**Comment by peckpeck** [comment]
PR updated

**Comment by amousset** [comment]
Ok, merging.

**Pull request merged**
