### PR TITLE
Fixes #10073: Redirect http to https in relay api

### PR DESCRIPTION
**Pull request by amousset**
https://www.rudder-project.org/redmine/issues/10073

### CODE REVIEW

**Comment by peckpeck** [comment]
Shouldn't you remove equivalent redirection code in webap-nossl ?

Are all our call already ssl based ?

**Comment by amousset** [comment]
we have some exceptions:

```
# Rule 2 - Don't use HTTP/S for these URLs to avoid breaking the compatibility for cURL
# clients (especially in Techniques)
RewriteCond %{REQUEST_URI} !^/rudder-(not-loaded|loading).html
RewriteCond %{REQUEST_URI} !^/uuid
RewriteCond %{REQUEST_URI} !^/inventories/?
RewriteCond %{REQUEST_URI} !^/inventory-updates/?
RewriteCond %{REQUEST_URI} !^/api/?
RewriteCond %{REQUEST_URI} !^/rudder/relay-api/?
```

All of this could go to common as we have a cond on http/https.

**Comment by peckpeck** [comment]
is the webapp calling remote run directly via ssl ?

**Comment by amousset** [comment]
yes: https://github.com/Normation/rudder/blob/master/rudder-web/src/main/resources/configuration.properties.sample#L75 and https://github.com/Normation/rudder-packages/blob/854a579624eabf76120a6c450e6e82f831c1805f/rudder-webapp/SOURCES/rudder-upgrade#L477

**Pull request merged**
