### PR TITLE
Fixes #9622: Fusioninventory is not tracked by check-rudder-health

### PR DESCRIPTION
**Pull request by ncharles**
https://www.rudder-project.org/redmine/issues/9622

### CODE REVIEW

**Comment by peckpeck** [comment]
You need to duplicate this pull request, after rudder 4.0 the check has been moved to the rudder-agent repository

**Comment by ncharles** [comment]
in branch 4.0, this is https://github.com/Normation/rudder-agent/pull/105

**Comment by ncharles** [comment]
OK, merging this PR

**Comment by ncharles** [comment]
OK, merging this PR

**Comment by ncharles** [comment]
OK, merging this PR

**Pull request merged**
