### PR TITLE
Fixes #8369: Rudder jetty init script broken

### PR DESCRIPTION
**Pull request by amousset**
https://www.rudder-project.org/redmine/issues/8369

### CODE REVIEW

**Comment by amousset** [comment]
The version check is already done in the init script.

**Comment by jooooooon** [comment]
This should also be fixed in 2.11 in :

`rudder-jetty/SOURCES/rudder-jetty.default:27:JAVA_MAJOR_VERSION=`${JAVA} -version 2>&1 | grep "^java version" | sed 's/java version "\([0-9]\+\.[0-9]\)\+\..*"/\1/'`
`

**Comment by jooooooon** [comment]
As for the duplicate version check, I propose instead to remove rudder-jetty/SOURCES/patches/jetty/jetty-init-check-java-version.patch, and keep the one in rudder-jetty/SOURCES/rudder-jetty.default because it's much easier to modify scripts than patches, and the error message is better there

**Comment by amousset** [comment]
@jooooooon Replaced by #950 for java detection, opened https://www.rudder-project.org/redmine/issues/8373 to remove the check from the init script.

**Pull request closed without merging**
