### PR TITLE
Fixes #14661: Remove relay sources from rudder-packages

### PR DESCRIPTION
**Pull request by amousset**
https://issues.rudder.io/issues/14661

### CODE REVIEW

**Comment by amousset** [comment]
Commit modified

**Comment by amousset** [comment]
Commit modified

**Comment by peckpeck** [comment]
Before removing this, you must first change debian rules and rpm specfile

**Comment by amousset** [comment]
PR replaced by https://github.com/Normation/rudder-packages/pull/1855

**Pull request closed without merging**
