### PR TITLE
Fixes #16675: rudder-metrics-reporting doesn't work with 5 000 nodes

### PR DESCRIPTION
**Pull request by ncharles**
https://issues.rudder.io/issues/16675

### CODE REVIEW

**Review by amousset — APPROVED** [review]

**Comment by ncharles** [comment]
OK, merging this PR

**Comment by ncharles** [comment]
OK, merging this PR

**Comment by ncharles** [comment]
OK, merging this PR

**Comment by ncharles** [comment]
OK, merging this PR

**Pull request merged**
